Avoid double freeing BPF resources
I have been noticing some crashes in the form of SIGSEGVs, and they seemed
to happen around the time we called some libbpf functions:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xfff087f7c714 pc=0xfff087f7c714]

runtime stack:
runtime.throw({0x1acc067?, 0x434110?})
	runtime/panic.go:992 +0x50
runtime.sigpanic()
	runtime/signal_unix.go:802 +0x1e8

goroutine 60 [syscall]:
runtime.cgocall(0x16150ec, 0x4000751948)
	runtime/cgocall.go:157 +0x54 fp=0x4000751910 sp=0x40007518d0 pc=0x40d7b4
github.com/aquasecurity/libbpfgo._Cfunc_bpf_link__destroy(0xffff780046d0)
	_cgo_gotypes.go:248 +0x3c fp=0x4000751940 sp=0x4000751910 pc=0xb4b44c
github.com/aquasecurity/libbpfgo.(*Module).Close.func1(0x4?)
	github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:314 +0x58 fp=0x4000751980 sp=0x4000751940 pc=0xb4e268
github.com/aquasecurity/libbpfgo.(*Module).Close(0x40003464b0)
	github.com/aquasecurity/libbpfgo@v0.2.5-libbpf-0.7.0/libbpfgo.go:314 +0xcc fp=0x40007519d0 sp=0x4000751980 pc=0xb4e14c
github.com/parca-dev/parca-agent/pkg/profiler.(*CgroupProfiler).Run.func3()
	github.com/parca-dev/parca-agent/pkg/profiler/profiler.go:290 +0x2c fp=0x40007519f0 sp=0x40007519d0 pc=0xb5901c
runtime.deferreturn()
	runtime/panic.go:436 +0x38 fp=0x4000751a30 sp=0x40007519f0 pc=0x4404d8
github.com/parca-dev/parca-agent/pkg/profiler.(*CgroupProfiler).Run(0x4000846000, {0x1d252e0, 0x400027ae80})
	github.com/parca-dev/parca-agent/pkg/profiler/profiler.go:361 +0xb70 fp=0x4000751d80 sp=0x4000751a30 pc=0xb58c30
github.com/parca-dev/parca-agent/pkg/target.(*ProfilerPool).Sync.func1()
	github.com/parca-dev/parca-agent/pkg/target/profiler_pool.go:158 +0x40 fp=0x4000751fd0 sp=0x4000751d80 pc=0xb5ddd0
runtime.goexit()
	runtime/asm_arm64.s:1259 +0x4 fp=0x4000751fd0 sp=0x4000751fd0 pc=0x474924
created by github.com/parca-dev/parca-agent/pkg/target.(*ProfilerPool).Sync
	github.com/parca-dev/parca-agent/pkg/target/profiler_pool.go:157 +0x208
[...]
```

The logs had a hint of what could be going on:
```
[...]
level=error ts=2022-04-21T12:47:07.060290116Z caller=profiler.go:321 labels="{__cgroup_path__=\"/sys/fs/cgroup/system.slice/docker-e9fafb1be949c1eb6d7432cf727bb9bfb57d703758f87267c7a67a1aa5f6c55f.scope/\", node=\"test\", systemd_unit=\"docker-e9fafb1be949c1eb6d7432cf727bb9bfb57d703758f87267c7a67a1aa5f6c55f.scope\"}" msg="close perf event" err="bad file descriptor"
```

I first double checked that `defer` was behaving as expected (see https://github.com/parca-dev/parca-agent/pull/343#discussion_r849566004 where
Kemal showed me how it actually worked in this case.

Long story short, we are double cleaning some resources, this means we are potentially double
closing some file descriptors (which is no bueno) but what it worse, we could potentially
double free memory / access freed memory (haven't verified which case it is!). This is
explained in the added comments.

Setting a breakpoint in GDB with `b bpf_link__destroy`, with this command to invoke it:
```shell
$ sudo gdb  --args dist/parca-agent --node=test --systemd-units=$UNIT --log-level=debug --kubernetes=false --insecure
```

shows some invalid links

```
(gdb) p *link
$22 = {detach = 0xaa0103e3d503245f, dealloc = 0xaa0003e1d2800004,
  pin_path = 0x92800c60d28004a8 <error: Cannot access memory at address 0x92800c60d28004a8>, fd = -1442839582, disconnected = true}
```

I have checked that we are passing [the conditions](https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L9761) to call the `detach` function:

```
(gdb) p link->disconnected
$4 = false
(gdb) p link->detach
$5 = (int (*)(struct bpf_link *)) 0x161a5d4 <bpf_link_perf_detach>
```

I think this behaviour might have been introduced in https://github.com/parca-dev/parca-agent/pull/343

While debugging this under GDB, I have seen some SIGBUSes. I haven't seen them without a debugger!

Let's explore the possibility of adding sanitizers to our build and dev environment, it should help us
understand and debug these kind of situations!